[window]
opacity = 0.90

[selection]
save_to_clipboard = true

[colors.primary]
  background = "#171421"

[colors.normal]
  black = "#171421"
  red = "#C01C28"
  green = "#26A269"
  yellow = "#A2734C"
  blue = "#12488B"
  magenta = "#A347BA"
  cyan = "#2AA1B3"
  white = "#D0CFCC"
